### ISSUE TITLE
Request for some basic examples on how to use Bing Maps in Angular

### ISSUE THREAD

**Issue by thor-schueler** [infusion-code/angular-maps#1]
@smithGit - Gern geschehen ;). I put a plunker out for a basic map with ng4

>https://plnkr.co/edit/KNOozNmAkxOtz30uCyug?p=preview

See issue Microsoft/Bing-Maps-V8-TypeScript-Definitions#15

**Comment by smithGit** [comment]
Vielen Dank.  I hoffe morgens hinein zu graben (wenn dass bedeutet etwas auf Deutsch).  Sam

**Comment by thor-schueler** [comment]
I put a bunch more plunks out there. See the readme of this repo for the links. I will add more examples with polygons soon. Closing this for now.

**Comment by smithGit** [comment]
Thank you, I am working with them now.  Most appreciated.  / Closed - no further requests.
