### ISSUE TITLE
Customn styling in angular-maps possible?

### ISSUE THREAD

**Issue by AxxitJdn** [infusion-code/angular-maps#101]
Is it possible to add customn map styling to the map? As explained here: https://docs.microsoft.com/en-us/bingmaps/articles/custom-map-styles-in-bing-maps it is possible to create a JSON with some map styling (e.g. water: red).

**Comment by AxxitJdn** [comment]
I noticed that the code for custom styling is on the main branch in GIT, however it is not released to NPM, are you planning on doing this?

**Comment by thor-schueler** [comment]
Should be included in version 6.0.2 (published today). Could you please confirm.
