### ISSUE TITLE
Map Service Injection Trouble

### ISSUE THREAD

**Issue by PaulGG** [infusion-code/angular-maps#104]
Hi. I have had a lot of trouble getting the injection of BingMapsService working properly. From delving through all open/closed issues and sparse documentation, I finally reached a solution to get the instance of the map object itself, using the method done in issue #29 . However, I am not happy with this result as it's not particularly clean. Whenever I inject the map instance like I would any other service, and add the BingMapService as a provider, none of the methods resolve/reject their promises, and the map instance is null.

Could anyone explain on how to properly inject the service to get map attributes?

**Comment by AxxitJdn** [comment]
In your html you can do something like this: 
`<x-map #xmap [Options]="_options" 
                         (MapPromise)="_processMapPromise($event)"
                         (MapService)="_processMapService($event)"`

**Comment by AxxitJdn** [comment]
you can catch the map by waiting for the $event to be resolved like this: 
` mapPromise.then(x => {
      this.map = x;
    });`

**Comment by thor-schueler** [comment]
@PaulGG: did this solve your problem? can I close this issue?

**Comment by PaulGG** [comment]
yes, all good
