### ISSUE TITLE
Support Angular 8.0 for Bing

### ISSUE THREAD

**Issue by danilvalov** [infusion-code/angular-maps#105]
Hi.
I got the following error in my angular@8 app:
```
Unhandled Promise rejection: Cannot assign to read only property 'prototype' of function 'class BingMapLabel extends MapLabel {
```
When I switch in my app to Angular 7.2 it works without problems.

How to fix it?

**My environment:**
"angular": "8.0.1"
"angular-maps": "6.0.1"
"bingmaps": "2.0.3"

**Comment by JoeMellon** [comment]
Any fix for this in the meantime?

**Comment by thor-schueler** [comment]
This has been included in version 6.0.2. Please verify.

**Comment by JoeMellon** [comment]
@thor-schueler Getting module errors now on all imports since update of 6.0.2

`error TS2307: Cannot find module 'angular-maps'.` Nothing in the package folder after npm install just bundle file.

**Comment by thor-schueler** [comment]
Apologies for this. Apparently, most of the dist was excluded from the tarball due to incorrect files property in the package.json. I unpublished 6.0.2 and will publish 6.0.3 shortly.

**Comment by thor-schueler** [comment]
This fix seems to break a number of things with labels and overlay... See #110. Need to investigate more...
