### ISSUE TITLE
angular-maps V6.0.2 does not work

### ISSUE THREAD

**Issue by LauraTGail** [infusion-code/angular-maps#109]
**Environment**
Angular version: 8.2.4
Angular maps version: 6.0.2

**Issue**
Cannot find module 'angular-maps'.

![image](https://user-images.githubusercontent.com/36442470/64945576-bcf6cc80-d868-11e9-8503-714a4d63fb50.png)

**Comment by thor-schueler** [comment]
Yes indeed. Just noticed that. Apparently, we had a "files" property creep into the package.json which in turn severely limited was was included in the 6.0.2 tarball. I unpublished 6.0.2, corrected the issue and published a new version 6.0.3. Apologies....
