### ISSUE TITLE
Several IMapOptions are not working

### ISSUE THREAD

**Issue by sskhokhar** [infusion-code/angular-maps#28]
There are several option of IMap which are not working like 
showMapTypeSelector: false,
disableZooming: true

Could you please look into it?

**Comment by thor-schueler** [comment]
Sure, what platform are you targeting? Bing and Google?

**Comment by thor-schueler** [comment]
I  suspect you are trying to target Google. Those two options you mentioned are not currently supported for Google. I did add support into 0.6.11, so please upgrade to that and try it out and let me know.

**Comment by thor-schueler** [comment]
Closing this as resolved.
