### ISSUE TITLE
How to get BingMap instance reference?

### ISSUE THREAD

**Issue by chuyelong** [infusion-code/angular-maps#29]
Hi there,

I would like to work on bing map directly after it is created. How can I get the reference?

Tried BingMapService, it's MapInstance is undefined.

Thanks for your help!

Yelong

**Comment by thor-schueler** [comment]
You can simply inject the MapService into your component. The actual map instance  (either a Microsoft Map object or a Google Map object)  is created when the MapComponent is initialized. Actually, two things happen: on the initialization of the MapComponent a promise is created and stored in the MapPromise member of the MapService. The the loading of the map infrastructure takes place asyncronously. As part of the that, the actual Google or Bing Map object is being created. That object is then stored in the MapInstance member of the MapService and the MapPromise is being resolved. 

So, if you want to interact with the MapService, inject it into your component. Then make sure you are using the MapComponent (<x-map/>) in your markup of your component. After component initialization, you can use the MapPromise or (if the promise is resolved) the MapInstance.

If you do not want to use the MapComponent, you can initialize the promise yourself by calling CreateMap member of the MapService (take a look of the implementation of the MapComponent as a go-by). However, this should generally not be necessary unless you want to build a UI from scratch without the components provided. 

Generally, the MapPromise is preferable, we included the MapInstance member only for convenience in situations when you can be sure that promise has been resolved (as, for example, in event handlers raised by interactions with the maps).

**Comment by chuyelong** [comment]
Thanks for your reply! 

It is what I tried. But I got MapInstance undefined, MapPromise never called.
This is my html, and component

 <div style="height: 100vh">
    <x-map #xmap [Options]="_options">
        <x-map-marker *ngFor="let m of markers"
            [Latitude]="m.latitude" 
            [Longitude]="m.longitude" 
            [IconInfo]="m.iconInfo"
            > 
            <x-info-box [DisableAutoPan]="true" [Title]="m.title" [Description]="m.info">
                <x-info-box-action [Label]="'Click Me'" (ActionClicked)="_click()"></x-info-box-action>
            </x-info-box>   
        </x-map-marker>
    </x-map>
</div>

My component is like below.

import { Component, OnInit, Input, ViewChild } from '@angular/core';
import { IBox, IMapOptions, MarkerTypeId, ILatLong, MapComponent, IMarkerOptions, IMarkerIconInfo, 
    BingMapService, BingMapAPILoader, BingMapServiceFactory,
    MapService, MapAPILoader, MapTypeId  } from "angular-maps";

@Component({
    selector: 'ctrl-map',
    templateUrl: './ctrl.map.component.html',
    styles: [],
    providers: [ 
        { provide: MapService, deps:[MapAPILoader], useClass: BingMapService }
    ]
})
export class CtrlMapComponent implements OnInit
{
    @ViewChild("xmap") xmap: MapComponent;
    @Input() markers: IMarker[];
    @Input() center: ILatLong;

   _options: IMapOptions = {
        disableBirdseye: false,
        disableStreetside: false,
        navigationBarMode: -1,
        mapTypeId: MapTypeId.mercator,
        zoom: 12
   };

    constructor(private _bingService: MapService)
    {
    }

    ngOnInit()
    {
        var promise = this._bingService.MapPromise;
        promise.then(r => {
            var map = r;
            debugger;
        });
        var instance = this._bingService.MapInstance;
        debugger;
    }
}


line "var map = r;" in ngOnInit never been called.

Could be anything wrong?

Thanks again for your help!

**Comment by thor-schueler** [comment]
Yes, this would never fire in your situation. You are creating a new instance of the map service in your component. The map service however should generally be a singleton service generated on the module level. Because of the scoping rules in dependency injection, Your component will use the MapService instance you are creating in your @component decorator as it is "closer" in scope. The MapComponent however will use the service instance created on the module level, which is also where the promise is being created. 

Removing your provider in the @component decorator should resolve that. I'll try to put a plunk out there later today to illustrate....

**Comment by chuyelong** [comment]
Then I have to provide MapService in Module, but code below shows error.
"Type 'typeof MapService' is not assignable to type 'Provider'."

```
providers: [
        { provide: MapAPILoader, deps: [], useFactory: MapServiceProviderFactory },
        MapService
    ]
```

**Comment by thor-schueler** [comment]
Could you post your entire module code where you are initializing the loader etc?

**Comment by chuyelong** [comment]
```
/// <reference path="../../node_modules/bingmaps/scripts/MicrosoftMaps/Microsoft.Maps.All.d.ts" />

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule, Routes } from '@angular/router';

import { MapModule, MapService, BingMapService, MapAPILoader, BingMapAPILoaderConfig, BingMapAPILoader, WindowRef, DocumentRef, MapServiceFactory, BingMapServiceFactory } from "angular-maps";

import { CtrlMapComponent } from './controls/ctrl.map.component';

@NgModule({
    imports: [
        CommonModule,
        FormsModule,

        MapModule.forRoot()        
    ],
    declarations: [
        CtrlMapComponent
    ],
    exports:[
        CommonModule,
        FormsModule,

        CtrlMapComponent
    ],
    providers: [
        { provide: MapAPILoader, deps: [], useFactory: MapServiceProviderFactory },
        MapService
    ]
})

export class AppSharedModule
{
}

export function MapServiceProviderFactory(){
    let bc: BingMapAPILoaderConfig = new BingMapAPILoaderConfig();
    bc.apiKey ="Amrk-TNjA0mdsSa74-mgwQ1Npd-lOhfPNi0x1sr5Kqx_zXz6zPS-Kr-uaAEaglN7"; // your bing map key
    bc.branch = "experimental"; 
        // to use the experimental bing brach. There are some bug fixes for
        // clustering in that branch you will need if you want to use 
        // clustering.
    return new BingMapAPILoader(bc, new WindowRef(), new DocumentRef());
  }
```

I have removed all unrelated lines(other import modules). MapService in providers has the problem.

**Comment by thor-schueler** [comment]
Ah yes, I see the problem now. A couple of releases back we moved all service instances to be local to the MapComponent to allow the use of multiple instances of the MapComponent in parallel. That means that the method I described above only works for components that are in the child scope of the MapComponent. Your component of course is in the parent scope of the MapComponent. 

I got to think about how to be expose the service. The easiest would be to expose it as an output. You could then bind to it and respond as soon as it becomes available. What do you think?

**Comment by chuyelong** [comment]
Yes, it would be great if it can be access through MapComponent's property, just like Box, Lat/Long, Zoom.

Thanks!

**Comment by thor-schueler** [comment]
Let me see whether I can get that in today or tomorrow... Should be straight forward...

**Comment by thor-schueler** [comment]
Question: I am wondering whether you really want the MapService or just the promise for the map object. I am thinking the latter, as this would give you all you need to directly interact with the map. The MapService  has a couple of methods that really should not be called outside the context of the map components. What do you think?

**Comment by chuyelong** [comment]
Agree, as least for me, I don't need service as long as I'm able to add geo objects and get the original map control.

Your project is about to wrap the markers/layers/infobox into Angular 2, but not provide additional service, right? If they can be exposed through MapComponent, it should be good enough.

**Comment by thor-schueler** [comment]
OK, please update to v0.6.12,,, Here is a working example in plunker: https://plnkr.co/edit/Ys4H9B3ZNqQH1Ux6emVm?p=preview 

Let me know whether this solves the issue...

**Comment by chuyelong** [comment]
Yes, it solved my issue.

Thanks a lot!

**Comment by Piyush25071990** [comment]
I have multiple marker on map and it is opening infobox on every marker.
i want that when i click on a marker  then infobox will show only for that marker.
Who can i do that ?
