### ISSUE TITLE
Get reference to Marker's PushPin and Metadata

### ISSUE THREAD

**Issue by chuyelong** [infusion-code/angular-maps#32]
How to get reference to marker's PushPin? And attache metadata to marker object? I tried ViewChildren, but only get reference to nativeElement.

Thanks!

**Comment by thor-schueler** [comment]
What are you trying to do? In the context of an event, the Pushpin model is passed to the handler as an argument, the metadata is on there.

**Comment by chuyelong** [comment]
We need to register some mouse events to markers, like mouseover/mouseout.

**Comment by thor-schueler** [comment]
I see….

Currently, the MapMarker only supports DragEnd and Click. The BingAPI supports additional events, but at the moment we are not wiring them up. That would be easy to change. At the moment, when you subscribe to click, $event argument has the following structure:

{
Marker: MapMarkerDirective,
      Click: MouseEvent,
      Location: ILatLong,
      Pixels: IPoint
}

Using $event.Marker.Metadata you can get to the metadata of the marker.

This pattern can easily be extended to the other events, however, in the spirit of x-maps we got to do it in such a way that is works as well with google. So let me check on that…

**Comment by thor-schueler** [comment]
I have added support for all marker events. Please update to v0.6.13. When using the events, subscribe to the appropriate emitter as in

        <x-map-marker [Latitude]="30" [Longitude]="90" [Title]="'My Marker'" [IconInfo]="{
                            markerType: _markerTypeId.RotatedImageMarker,
                            url: 'http://localhost:4200/assets/marker.png',
                            scale: 0.05,
                            size: { width: 30, height: 30 },
                            markerOffsetRatio: { x: 0.5, y: 1 },
                            rotation: 30
                        }" (DblClick)="_event($event)" (MarkerClick)="_event($event)">

The event argument is of type IMarkerEvent and has the following format:

     {
           Marker: MapMarkerDirective,
           Click: MouseEvent,
           Location: ILatLong,
           Pixels: IPoint
     }
