### ISSUE TITLE
Bing Maps - Changing Polygon Color properties

### ISSUE THREAD

**Issue by dahovey** [infusion-code/angular-maps#36]
Found an issue with changing FillColor and/or StrokeColor after the polygon has been created. It only occurs with Bing. When consumer is using both opacity and color, then if you change the color the opacity value isn't used.

I believe inside `map-polygon.ts` in `GeneratePolygonChangeSet`, if present, the opacity value should be sent along with color changes.
[map-polygon.ts](https://github.com/infusion-code/angular-maps/blob/8acbc1f01321d9d64cc6863b69a693cf5973872e/src/components/map-polygon.ts#L471-L491)

Here is plunker showing issue. Click button above map to trigger change.
[https://plnkr.co/edit/xxTSUqc6uHgVYy12mZqP?p=preview](https://plnkr.co/edit/xxTSUqc6uHgVYy12mZqP?p=preview)

**Comment by dahovey** [comment]
It this sounds reasonable I can make changes in my forked version and use the existing pull request? Or create new one?

**Comment by thor-schueler** [comment]
A new pull request is preferable if the fix is not related to the feature enhancement (doesn’t sound like it). Apologies for being slow on the response. This week’s busy ;)

**Comment by dahovey** [comment]
Makes sense. No worries on response. I created a temporary npm package for my combined changes so I can keep moving on my end.

I created pull request #37 which includes the minor fix.

**Comment by thor-schueler** [comment]
Thanks for discovering and fixing! It's merged in the codebase, but I'll keep this issue open until the next version is published.

**Comment by thor-schueler** [comment]
This has been incorporated and published in version 0.6.14
