### ISSUE TITLE
Bing Maps - interaction with  x-info-box

### ISSUE THREAD

**Issue by krooshua** [infusion-code/angular-maps#38]
Hi @thor-schueler!
I see that you added new mouse events for map-markers and this is great!
But how can I show/hide info-box from this event?
Tried to use InfoBoxService and MarkerService, but as I can see the new instance of services is provided in the component, and I can't change the Visible value of info-box.

Thanks for any advice!

**Comment by krooshua** [comment]
Ok, I've implemented show/hide logic via *ngIf on info-box and [Visible]="true".
```
<x-info-box *ngIf="visible" 
	[Visible]="true" 
	[DisableAutoPan]="true"
        [Title]="'Title'"
	[Latitude]="latitude" 
	[Longitude]="longitude">
</x-info-box>
```
But for me, this still looks like a hack :)
Or this is the only one possibility?

**Comment by thor-schueler** [comment]
So there are two different approaches: 

1. Make the InfoBox a child of the marker (nest it inside the marker markup). In that situation you will not have to do anything, it will wire up automatically. Check out the plunk at https://plnkr.co/T76hHj as an example. The major drawback of that approach is that you have a separate infobox per marker, which bloats your expanded markup if you have more than a few markers.

2. Create one InfoBox outside the markers. In that situation, you want to bind [Visible] to a variable. On the marker click event, you would:

-  move the box by updating the bound lat/long variables with the info from the marker event argument (with is IMarkerEvent and contains lat/long)
- set the contents of the infobox based either on the marker properties (mark of the IMarkerEvent) or the Marker Metadata (if you have custom stuff you want to show in the InfoBox). 
- Manipulate the variable bound to Visible to show/hide the box.

The advantage of 2) is that you have only one box, which is good if you have a ton of markers. The disadvantage is that you do more in code. 

Hope that helps.
