### ISSUE TITLE
Cannot find namespace 'Microsoft'.

### ISSUE THREAD

**Issue by vijaygawade18** [infusion-code/angular-maps#44]
Hi @thor-schueler, I am getting this issue. 
 
E:/Tyco/project/working-copy/TYC023/tyco-web/angular-master/node_modules/angular-maps/dist/src/models/bingMaps/binginfowindow.d.ts(7                                                  ,27): error TS2503: Cannot find namespace 'Microsoft'.
E:/Tyco/project/working-copy/TYC023/tyco-web/angular-master/node_modules/angular-maps/dist/src/models/bingMaps/binglayer.d.ts(32,25)                                                  : error TS2503: Cannot find namespace 'Microsoft'.
E:/Tyco/project/working-copy/TYC023/tyco-web/angular-master/node_modules/angular-maps/dist/src/models/bingMaps/bingmarker.d.ts(63,27                                                  ): error TS2503: Cannot find namespace 'Microsoft'.
E:/Tyco/project/working-copy/TYC023/tyco-web/angular-master/node_modules/angular-maps/dist/src/models/bingMaps/bingspiderclustermark                                                  er.d.ts(7,12): error TS2503: Cannot find namespace 'Microsoft'.
E:/Tyco/project/working-copy/TYC023/tyco-web/angular-master/node_modules/angular-maps/dist/src/services/bingMaps/bingmapservice.d.ts                                                  (40,27): error TS2503: Cannot find namespace 'Microsoft'.
E:/Tyco/project/working-copy/TYC023/tyco-web/angular-master/node_modules/angular-maps/dist/src/services/bingMaps/bingmapservice.d.ts

**Comment by thor-schueler** [comment]
@vijaygawade18: looks like you are currently not loading the bing types.  Those are currently ncessary even if you work on a google project.  These are a compile time only dependency. Can you please check a few things for me:

- check in your node_modules folder for the version of bingmaps do you have installed. Bingmap introduced a breaking change from 1.8.* to 2.0.0 by renaming the 'scripts' folder to 'types'.
- make sure you follow the instructions in the Readme -> Import module and include     

/// <reference path="node_modules/bingmaps/scripts/MicrosoftMaps/Microsoft.Maps.All.d.ts" />  

or 

/// <reference path="node_modules/bingmaps/types/MicrosoftMaps/Microsoft.Maps.All.d.ts" /> 

depending on the version of the bingmaps module on the top of you app module ts file. 

This should hopefully solve your issue.

**Comment by vijaygawade18** [comment]
Hi @thor-schueler i am sorry  i couldn't reply to your comment.
I tried this solution but i am getting same issue.

I have included /// <reference path="node_modules/bingmaps/scripts/MicrosoftMaps/Microsoft.Maps.All.d.ts" /> this in app.module file and updated the version of Bingmap from 1.8 to 2.0.0.
Can you please tell me if i am missing out something.

Thanks!!

**Comment by thor-schueler** [comment]
Interesting. Could you please include your package.json, tsconfig.json and the app.module file? 

Also, could you please confirm that bingmaps/scripts/MicrosoftMaps/Microsoft.Maps.All.d.ts actually exists in the node_modules folder of your project?

**Comment by vijaygawade18** [comment]
There isn't script folder in bingmaps library so as of now i have included `/// <reference path="node_modules/bingmaps/types/MicrosoftMaps/Microsoft.Maps.All.d.ts" />` in app.modules file.

This is my tsconfig.json: 
`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "noLib": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015"],
    "sourceMap": true,
    "pretty": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noFallthroughCasesInSwitch": true,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules"
    ],
    "types": [
      "node"
    ]
  },
  "files": [
    "gulpfile.ts",
    "tools/manual_typings/seed/autoprefixer.d.ts",
    "tools/manual_typings/seed/cssnano.d.ts",
    "tools/manual_typings/seed/express-history-api-fallback.d.ts",
    "tools/manual_typings/seed/istream.d.ts",
    "tools/manual_typings/seed/karma.d.ts",
    "tools/manual_typings/seed/merge-stream.d.ts",
    "tools/manual_typings/seed/open.d.ts",
    "tools/manual_typings/seed/operators.d.ts",
    "tools/manual_typings/seed/slash.d.ts",
    "tools/manual_typings/seed/systemjs-builder.d.ts",
    "tools/manual_typings/seed/tildify.d.ts"
  ],
  "exclude": [
    "node_modules",
    "dist"
  ],
  "compileOnSave": false
}
`

and package.json

`{

  "scripts": {
    "build.dev": "gulp build.dev --color --env-config dev",
    "build.dev.watch": "gulp build.dev.watch --color",
    "build.e2e": "gulp build.e2e --color",
    "build.prod": "gulp build.prod --color --env-config prod --build-type prod",
    "build.prod.exp": "gulp build.prod.aot --color --env-config prod --build-type prod",
    "build.prod.rollup.aot": "gulp build.prod.rollup.aot --color --env-config prod --build-type prod",
    "build.prod.aot": "gulp build.prod.aot --color --env-config prod --build-type prod",
    "build.test": "gulp build.test --color",
    "test.watch": "gulp test.watch --color",
    "generate.manifest": "gulp generate.manifest --color",
    "e2e": "protractor",
    "e2e.live": "protractor --elementExplorer",
    "gulp": "gulp",
    "i18n": "ng-xi18n -p src/client/tsconfig.json && gulp clean.i18n",
    "lint": "gulp tslint",
    "karma": "karma",
    "karma.start": "karma start",
    "postinstall": "gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner",
    "reinstall": "npm cache clean && npm install",
    "serve.coverage": "gulp serve.coverage --color",
    "serve.dev": "gulp serve.dev --color --env-config dev",
    "serve.e2e": "gulp serve.e2e --color",
    "serve.prod": "gulp serve.prod --color --env-config prod --build-type prod",
    "serve.prod.aot": "gulp serve.prod.aot --color --env-config prod --build-type prod",
    "serve.prod.exp": "gulp serve.prod.aot --color --env-config prod --build-type prod",
    "serve.prod.rollup.aot": "gulp serve.prod.rollup.aot --color --env-config prod --build-type prod",
    "start": "gulp serve.dev --color",
    "start.deving": "gulp start.deving --color",
    "tasks.list": "gulp --tasks-simple --color",
    "test": "gulp test --color",
    "e2e.ci": "gulp build.prod --color && gulp build.e2e --color && gulp e2e --color",
    "tests.all": "npm test && npm run e2e.ci",
    "webdriver-start": "webdriver-manager start",
    "webdriver-update": "node_modules/protractor/bin/webdriver-manager update",
    "compodoc": "node_modules/.bin/compodoc -p src/client/tsconfig.json",
    "serve.compodoc": "node_modules/.bin/compodoc -s"
  },
  "author": "Minko Gechev <mgechev>",
  "license": "MIT",
  "devDependencies": {
    "@angular/compiler-cli": "4.0.0",
    "@angular/platform-server": "4.0.0",
    "@types/async": "2.0.32",
    "@types/browser-sync": "0.0.34",
    "@types/express": "4.0.33",
    "@types/gulp": "3.8.32",
    "@types/gulp-filter": "3.0.29",
    "@types/gulp-load-plugins": "0.0.28",
    "@types/gulp-protractor": "1.0.29",
    "@types/gulp-sass": "0.0.29",
    "@types/gulp-util": "^3.0.33",
    "@types/jasmine": "2.5.41",
    "@types/moment": "2.13.0",
    "@types/moment-timezone": "0.2.35",
    "@types/node": "6.0.45",
    "@types/rimraf": "0.0.28",
    "@types/run-sequence": "0.0.28",
    "@types/selenium-webdriver": "2.53.39",
    "@types/systemjs": "0.19.31",
    "@types/yargs": "6.5.0",
    "@types/zone.js": "0.0.27",
    "angular2-busy": "2.0.4",
    "async": "2.1.1",
    "autoprefixer": "6.5.1",
    "boost-js": "0.5.0",
    "browser-sync": "2.17.3",
    "canvasjs": "^1.8.1",
    "codelyzer": "^3.0.1",
    "compodoc": "0.0.40",
    "connect-history-api-fallback": "1.3.0",
    "cssnano": "3.7.7",
    "deep-extend": "0.4.1",
    "event-stream": "3.3.4",
    "express": "~4.14.0",
    "express-history-api-fallback": "2.0.0",
    "font-awesome": "4.7.0",
    "gulp": "3.9.1",
    "gulp-cached": "1.1.0",
    "gulp-concat": "2.6.0",
    "gulp-concat-css": "2.3.0",
    "gulp-filter": "4.0.0",
    "gulp-inject": "4.1.0",
    "gulp-inline-ng2-template": "4.0.0",
    "gulp-load-plugins": "1.3.0",
    "gulp-plumber": "~1.1.0",
    "gulp-postcss": "6.2.0",
    "gulp-progeny": "0.3.1",
    "gulp-protractor": "3.0.0",
    "gulp-rename": "1.2.2",
    "gulp-replace": "0.5.4",
    "gulp-sass": "3.0.0",
    "gulp-sourcemaps": "2.2.0",
    "gulp-template": "4.0.0",
    "gulp-tslint": "8.0.0",
    "gulp-typescript": "3.0.2",
    "gulp-uglify": "2.0.0",
    "gulp-util": "^3.0.7",
    "gulp-watch": "4.3.10",
    "is-ci": "1.0.9",
    "isstream": "0.1.2",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "3.0.0",
    "karma": "~1.3.0",
    "karma-chrome-launcher": "~2.0.0",
    "karma-coverage": "1.1.1",
    "karma-jasmine": "~1.1.0",
    "karma-mocha-reporter": "2.2.0",
    "karma-remap-istanbul": "0.2.1",
    "merge-stream": "1.0.0",
    "minimatch": "3.0.3",
    "open": "0.0.5",
    "pluralize": "5.0.0",
    "proj4": "2.4.3",
    "protractor": "4.0.14",
    "remap-istanbul": "0.8.4",
    "rimraf": "2.5.4",
    "rollup": "0.41.4",
    "rollup-plugin-commonjs": "7.0.1",
    "rollup-plugin-includepaths": "0.2.1",
    "rollup-plugin-node-resolve": "2.0.0",
    "run-sequence": "1.2.2",
    "semver": "5.3.0",
    "serve-static": "1.11.1",
    "slash": "~1.0.0",
    "supports-color": "3.1.2",
    "systemjs-builder": "0.15.34",
    "tildify": "1.2.0",
    "traceur": "0.0.111",
    "ts-node": "^3.3.0",
    "tslint": "^5.1.0",
    "typescript": "2.3.4",
    "walk": "2.3.9",
    "yargs": "6.0.0"
  },
  "dependencies": {
    "@angular/animations": "4.0.0",
    "@angular/cdk": "2.0.0-beta.8",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/material": "2.0.0-beta.8",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "@angular/service-worker": "1.0.0-beta.6",
    "@types/bingmaps": "0.0.0",
    "@types/moment-timezone": "0.2.35",
    "@types/proj4": "2.3.4",
    "angular-maps": "^0.7.1",
    "angular2-highcharts": "0.5.5",
    "angular2-image-upload": "0.6.6",
    "angular2-toaster": "4.0.1",
    "angular2gridster": "0.6.3",
    "bingmaps": "^2.0.0",
    "bootstrap": "3.3.7",
    "core-js": "2.4.1",
    "google-maps-angular2": "1.1.2",
    "highcharts-border-radius": "0.0.2",
    "intl": "1.2.5",
    "jquery": "3.1.1",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13",
    "ng-dynamic-component": "^1.0.8",
    "ng2-simple-autocomplete": "0.6.0",
    "ng2-translate": "^5.0.0",
    "ngx-chips": "^1.5.3",
    "ngx-cookie": "^1.0.0",
    "ngx-tooltip": "0.0.9",
    "ngx-uploader": "4.0.0",
    "ramda": "0.25.0",
    "rxjs": "5.2.0",
    "systemjs": "0.19.41",
    "tslib": "1.8.0",
    "zone.js": "0.8.4"
  }
}
`

app.module.ts:

`import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { APP_BASE_HREF } from '@angular/common';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { ChartModule } from 'angular2-highcharts';
import { FormsModule } from '@angular/forms';
import { BusyModule, BusyConfig } from 'angular2-busy';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { GridsterModule } from 'angular2gridster';
import { ToasterModule } from 'angular2-toaster';

import { TagInputModule } from 'ngx-chips';

import { CookieModule } from 'ngx-cookie';

import { SharedModule } from './shared/shared.module';

import { SearchInfoModule } from './containers/search-info/search-info.module';
import { DeviceAdditionalInfoModule } from './containers/dashboard/rdc/device-additional-info/device-additional-info.module';
import {
  URL_CONSTANT,
  UrlConstant
} from './shared/services/util/url.constants';

import { AppComponent } from './app.component';
import { routes } from './app.routes';
import { SharedService } from './shared/services/shared-service/shared.service';

import { NavbarLPService } from './shared/components/navbar-lp/navbar-lp.service';

import { HttpService } from './shared/services/util/http-request.service';
import { LayoutModule } from './shared/components/layout/layout.module';
import { ModalPopupModule } from './shared/components/modal-popup/modal-popup.module';

import { RdcModule } from './containers/dashboard/rdc/rdc.module';
import { LpManagerModule } from './containers/dashboard/lp-manager/lp-manager.module';
import { StoresModule } from './containers/dashboard/rdc/stores/stores.module';
import { DeviceModule } from './containers/dashboard/rdc/device/device.module';
import { NoResultModule } from './shared/components/404/404.module';
import { LoginModule } from './containers/login/login.module';
import { ForgetPasswordModule } from './containers/forget-password/forget-password.module';
import { AuthenticationService } from './shared/services/shared-service/authentication.service';
import { LpAuthGuard } from './guards/lp-auth.guard';
import { RdcAuthGuard } from './guards/rdc-auth.guard';
import { RdcAgentAuthGuard } from './guards/rdc-agent.guard';
import { SaveFormsGuard } from './guards/save-forms-guard';
import { CustomerModule } from './containers/dashboard/rdc/customer/customer.module';
import { AssignedModule } from './containers/dashboard/rdc-agent/assigned-to-me/assigned.module';
import { CustomerServices } from './containers/dashboard/rdc/customer/customer.services';
import { RdcAgentModule } from './containers/dashboard/rdc-agent/rdc-agent.module';
import { UserModule } from './containers/dashboard/rdc/user/user.module';
import { UserService } from './containers/dashboard/rdc/user/user.service';
import {
  AverageLossListService
} from './containers/dashboard/lp-manager/lp-alarm-average-loss/lp-alarm-average-loss-list/lp-alarm-average-loss-list.service';
import { HierarchyService } from './features/customers/customer-detail-create-hierarchy/customer-detail-create-hierarchy.service';
import { ResetPasswordModule } from './containers/reset-password/reset-password.module';
import { LpStoreModule } from './containers/dashboard/lp-manager/lp-store/lp-store.module';
import { AlarmAverageLossModule } from './containers/dashboard/lp-manager/lp-alarm-average-loss/lp-alarm-average-loss.module';
import { DeviceAssociationModule } from './containers/dashboard/rdc/device-association/device-association.module';
import { DeviceAssociationService } from './containers/dashboard/rdc/device-association/device-association.service';
import { LpAlertsService } from './containers/dashboard/lp-manager/lp-alerts/lp-alerts.service';
import { LpStoreService } from './containers/dashboard/lp-manager/lp-store/lp-store.service';
import { CreateCustomersService } from './containers/dashboard/rdc/customer/create-customers/create-customers.service';

/// <reference path="node_modules/bingmaps/types/MicrosoftMaps/Microsoft.Maps.All.d.ts" />

const CONTAINER_MODULES = [
  LayoutModule,
  RdcModule,
  LpManagerModule,
  RdcAgentModule,
  StoresModule,
  CustomerModule,
  AssignedModule,
  UserModule,
  DeviceAssociationModule,
  DeviceModule,
  SearchInfoModule,
  DeviceAdditionalInfoModule,
  NoResultModule,
  ModalPopupModule,
  LoginModule,
  ForgetPasswordModule,
  ResetPasswordModule,
  ToasterModule,
  LpStoreModule,
  AlarmAverageLossModule
];

@NgModule({
  imports: [
    CookieModule.forRoot(),
    BrowserModule,
    HttpModule,
    CONTAINER_MODULES,
    SharedModule.forRoot(),
    RouterModule.forRoot(routes, {useHash: true}),
    ChartModule.forRoot(require('highcharts')),
    CommonModule,
    BusyModule.forRoot(
      new BusyConfig({
        message: '',
        backdrop: true,
        wrapperClass: 'busy-class'
      })
    ),
    BrowserAnimationsModule,
    GridsterModule,
    TagInputModule,
    FormsModule
  ],
  declarations: [AppComponent],
  providers: [
    {
      provide: APP_BASE_HREF,
      useValue: '<%= APP_BASE %>'
    },
    {
      provide: URL_CONSTANT,
      useValue: UrlConstant
    },
    LpAuthGuard,
    RdcAuthGuard,
    RdcAgentAuthGuard,
    SaveFormsGuard,
    AuthenticationService,
    SharedService,
    HttpService,
    NavbarLPService,
    CustomerServices,
    LpAlertsService,
    UserService,
    DeviceAssociationService,
    AverageLossListService,
    HierarchyService,
    LpStoreService,
    CreateCustomersService
  ],
  bootstrap: [AppComponent]

})
export class AppModule {
}

`

**Comment by thor-schueler** [comment]
Yes, sorry. 'Types' is correct. My mistake. 

However, I do not see the ///<reference... in your app.module.ts. Where are you referencing? Keep in mind that ///<reference... must always be on the very top of the file....

**Comment by vijaygawade18** [comment]
@thor-schueler  I am getting "node_modules/bingmaps/types/MicrosoftMaps/Microsoft.Maps.All.d.ts" not found If /// <reference.. is included on the top of the file. 

so keeping this in mind i have included /// <reference.. like this.

`import { NgModule } from '@angular/core';
/// <reference path="node_modules/bingmaps/types/MicrosoftMaps/Microsoft.Maps.All.d.ts" />
import { BrowserModule } from '@angular/platform-browser';
import { APP_BASE_HREF } from '@angular/common';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { ChartModule } from 'angular2-highcharts';
import { FormsModule } from '@angular/forms';
import { BusyModule, BusyConfig } from 'angular2-busy';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { GridsterModule } from 'angular2gridster';
import { ToasterModule } from 'angular2-toaster';

import { TagInputModule } from 'ngx-chips';

import { CookieModule } from 'ngx-cookie';

import { SharedModule } from './shared/shared.module';

import { SearchInfoModule } from './containers/search-info/search-info.module';
import { DeviceAdditionalInfoModule } from './containers/dashboard/rdc/device-additional-info/device-additional-info.module';
import {
  URL_CONSTANT,
  UrlConstant
} from './shared/services/util/url.constants';

import { AppComponent } from './app.component';
import { routes } from './app.routes';
import { SharedService } from './shared/services/shared-service/shared.service';

import { NavbarLPService } from './shared/components/navbar-lp/navbar-lp.service';

import { HttpService } from './shared/services/util/http-request.service';
import { LayoutModule } from './shared/components/layout/layout.module';
import { ModalPopupModule } from './shared/components/modal-popup/modal-popup.module';

import { RdcModule } from './containers/dashboard/rdc/rdc.module';
import { LpManagerModule } from './containers/dashboard/lp-manager/lp-manager.module';
import { StoresModule } from './containers/dashboard/rdc/stores/stores.module';
import { DeviceModule } from './containers/dashboard/rdc/device/device.module';
import { NoResultModule } from './shared/components/404/404.module';
import { LoginModule } from './containers/login/login.module';
import { ForgetPasswordModule } from './containers/forget-password/forget-password.module';
import { AuthenticationService } from './shared/services/shared-service/authentication.service';
import { LpAuthGuard } from './guards/lp-auth.guard';
import { RdcAuthGuard } from './guards/rdc-auth.guard';
import { RdcAgentAuthGuard } from './guards/rdc-agent.guard';
import { SaveFormsGuard } from './guards/save-forms-guard';
import { CustomerModule } from './containers/dashboard/rdc/customer/customer.module';
import { AssignedModule } from './containers/dashboard/rdc-agent/assigned-to-me/assigned.module';
import { CustomerServices } from './containers/dashboard/rdc/customer/customer.services';
import { RdcAgentModule } from './containers/dashboard/rdc-agent/rdc-agent.module';
import { UserModule } from './containers/dashboard/rdc/user/user.module';
import { UserService } from './containers/dashboard/rdc/user/user.service';
import {
  AverageLossListService
} from './containers/dashboard/lp-manager/lp-alarm-average-loss/lp-alarm-average-loss-list/lp-alarm-average-loss-list.service';
import { HierarchyService } from './features/customers/customer-detail-create-hierarchy/customer-detail-create-hierarchy.service';
import { ResetPasswordModule } from './containers/reset-password/reset-password.module';
import { LpStoreModule } from './containers/dashboard/lp-manager/lp-store/lp-store.module';
import { AlarmAverageLossModule } from './containers/dashboard/lp-manager/lp-alarm-average-loss/lp-alarm-average-loss.module';
import { DeviceAssociationModule } from './containers/dashboard/rdc/device-association/device-association.module';
import { DeviceAssociationService } from './containers/dashboard/rdc/device-association/device-association.service';
import { LpAlertsService } from './containers/dashboard/lp-manager/lp-alerts/lp-alerts.service';
import { LpStoreService } from './containers/dashboard/lp-manager/lp-store/lp-store.service';
import { CreateCustomersService } from './containers/dashboard/rdc/customer/create-customers/create-customers.service';


const CONTAINER_MODULES = [
  LayoutModule,
  RdcModule,
  LpManagerModule,
  RdcAgentModule,
  StoresModule,
  CustomerModule,
  AssignedModule,
  UserModule,
  DeviceAssociationModule,
  DeviceModule,
  SearchInfoModule,
  DeviceAdditionalInfoModule,
  NoResultModule,
  ModalPopupModule,
  LoginModule,
  ForgetPasswordModule,
  ResetPasswordModule,
  ToasterModule,
  LpStoreModule,
  AlarmAverageLossModule
];

@NgModule({
  imports: [
    CookieModule.forRoot(),
    BrowserModule,
    HttpModule,
    CONTAINER_MODULES,
    SharedModule.forRoot(),
    RouterModule.forRoot(routes, {useHash: true}),
    ChartModule.forRoot(require('highcharts')),
    CommonModule,
    BusyModule.forRoot(
      new BusyConfig({
        message: '',
        backdrop: true,
        wrapperClass: 'busy-class'
      })
    ),
    BrowserAnimationsModule,
    GridsterModule,
    TagInputModule,
    FormsModule
  ],
  declarations: [AppComponent],
  providers: [
    {
      provide: APP_BASE_HREF,
      useValue: '<%= APP_BASE %>'
    },
    {
      provide: URL_CONSTANT,
      useValue: UrlConstant
    },
    LpAuthGuard,
    RdcAuthGuard,
    RdcAgentAuthGuard,
    SaveFormsGuard,
    AuthenticationService,
    SharedService,
    HttpService,
    NavbarLPService,
    CustomerServices,
    LpAlertsService,
    UserService,
    DeviceAssociationService,
    AverageLossListService,
    HierarchyService,
    LpStoreService,
    CreateCustomersService
  ],
  bootstrap: [AppComponent]

})
export class AppModule {
}

`
Is there anything wrong in my tsconfig.json and package.json files as i am still getting the same issue.

**Comment by thor-schueler** [comment]
Does the Microsoft.Maps.All.d.ts exist in the location? Also, it looks like that there is an import above the ///<reference...

**Comment by vijaygawade18** [comment]
Hi @thor-schueler Including the /// <reference.. to the extreme top of the app.module.ts file with the correct path solves the "Microsoft" namespace issue.

Thanks you so much for your prompt help!! :1st_place_medal:  :)
