### ISSUE TITLE
Rendering Markers and Polylines in a separate window

### ISSUE THREAD

**Issue by drewteachout** [infusion-code/angular-maps#50]
In my application I use GoldenLayout to display several components on one screen with the ability to drag and drop windows, and pop them out into separate windows. My map is one of these components. Everything works perfectly when the map is docked, but as soon as I pop it out into a separate window the map will no longer update the UI at all. I have two lists that I loop through in an *ngFor of custom objects that have all the various pieces of information I need to create the marker and associated infobox (i.e. lat, long, iconUrl, and several variables I use in the description of the infobox). Going through the debugger I can see that when it's popped out the events are still triggering and the map component is receiving them and the two lists I use are holding the proper data, but it won't appear in the map. I've attached a screenshot of the error I got every time the map receives the event that tells it what to display.

![map_error](https://user-images.githubusercontent.com/20385315/33559530-1a4964cc-d8db-11e7-9c2a-c30cdc73d954.png)

I understand this is a complex issue, but I was wondering if you had any insight on what may be preventing the map from updating markers and polylines even though the data has changed. Any help you can offer is greatly appreciated!

**Comment by thor-schueler** [comment]
I do not have any experience with GoldenLayout, but the error message you have posted seems to implicate that that the popout is messing with the change detection. 

I would suggest you post an issue on the GoldenLayout repo to see whether they have any insight. 

https://github.com/deepstreamIO/golden-layout/issues/75 might be helpful as well...

**Comment by thor-schueler** [comment]
@drewteachout - did you find out anything more about that?

**Comment by drewteachout** [comment]
I'm still waiting on a reply from the GoldenLayout guys. Haven't figured anything out on my own debug efforts. I agree with your assessment that it seems like a GoldenLayout issue

**Comment by drewteachout** [comment]
Got nothing from the GoldenLayout guys. However, was eventually able to debug the issue. You guys were right. It was a GoldenLayout problem and nothing to do with angular-maps. Sorry for the confusion!
