### ISSUE TITLE
Map not loading when populating markers and polylines with an empty list

### ISSUE THREAD

**Issue by drewteachout** [infusion-code/angular-maps#51]
In my code I have two separate lists that have objects with the information I need to make markers and polylines. My html (seen below) works great when I have any data, but as soon as my list is empty the map stops displaying. I would like to just display an empty map if I have no available data. Is there a reason the map is not displaying?

```
<div class="map">
  <x-map #xmap [Options]="options" [Latitude]="latitude" [Longitude]="longitude">
    <x-map-marker *ngFor="let loc of locationArray"
      [Latitude]="loc.latitudeNumber"
      [Longitude]="loc.longitudeNumber"
      [IconUrl]="'asset url'">
      <x-info-box
        [Title]="loc.SLIC"
        [Description]="'My Description">
      </x-info-box>
    </x-map-marker>
    <x-map-polyline *ngFor="let key of keyArray"
      [Path]="linkMap.get(key)[0].points"
      [StrokeWeight]=5
      [StrokeColor]="masterColor">
      <x-info-box *ngFor="let line of linkMap.get(key)"
        [Title]="My Title"
        [Description]="My Description">
      </x-info-box>
    </x-map-polyline>
  </x-map>
</div>
```

These are the values of the arrays when the map isn't displaying.

locationArray = [];
keyArray = [];

**Comment by thor-schueler** [comment]
Should work fine. The ngFor should simple expand to zero markers or polylines. Can you put a plunk up so I can have a closer look? 

Are you sure that those are in fact empty arrays as opposed to null? Is there any error in the console?

In the meanwhile, you could wrap the marker and polyline directive with a <ng-container *ngIf="locationArray.length > 0"> and <ng-container *ngIf="keyArray.length > 0">...

**Comment by drewteachout** [comment]
After rerunning ng serve the empty map appears to show up. There is no issue anymore. Sorry for the confusion
