### ISSUE TITLE
Clearing clusters

### ISSUE THREAD

**Issue by vijaygawade18** [infusion-code/angular-maps#52]
Hi @thor-schueler I am having issue while loading clearing the clusters and loading the new clusters according to new information coming from the data.

I have seen the google map api which has a functionality to clear the clusters. Can you please help me with this.

Thanks!!

**Comment by thor-schueler** [comment]
You should not need to do that. When you bind your data to the markers (generally with an ngFor inside your cluster layer component) changes to your data structure will lead to an automatic re-expansion of the markers in your cluster-layer. If you would please put a plunk of your code together, I will have a look. There are also a number of examples for cluster markers in the example section...

**Comment by vijaygawade18** [comment]
Actually i want to clear the old clusters from the map when clicked on button.

**Comment by thor-schueler** [comment]
Yes, simply, in your button event, remove any items from the array you are using the drive the ngFor. If that does not do the trick, there is a bug.... Let me know...

**Comment by thor-schueler** [comment]
I did put together an example at https://plnkr.co/o4r20z. It shows how to clear markers in a clustered layer by manipulating the bound data. However, there was a bug in the code for both normal and cluster layers that would not correctly remove existing markers. This has been corrected in 0.7.3...

**Comment by vijaygawade18** [comment]
Hi @thor-schueler upgrading from 0.7.2 to 0.7.3 solved my problem.

Appreciate your help !! 
Thanks :+1:  :1st_place_medal:
