### ISSUE TITLE
Is there a way to create a custom html infoBox?

### ISSUE THREAD

**Issue by drewteachout** [infusion-code/angular-maps#57]
In the Bing Maps library there is an htmlContent attribute to infoBoxes that lets you use custom html. I don't see this attribute as part of x-map-marker? Is there a different way of doing this, or does this feature need to be added?

**Comment by k-spen** [comment]
I am trying to get this code working (yes, I see that you mentioned it doesn't work).  I think I'm getting there but I run into a problem with **this._infoBoxRef**.  This is obviously referencing the <x-infobox ...>.   How do I get this to not be undefined?  I have it as private _infoBoxRef: ElementRef but this isn't working (obviously no value is getting set).  I can't figure out how to get the value of the x-infobox into it.  Can you help with this?  Thanks!

**Comment by thor-schueler** [comment]
@k-spen: actually, there is no ```<x-infobox>``` in this example. It's place has been taken by ```<div #infoBox ...>```

To get a reference, use a ViewChild directive, as in 

```
    @ViewChild('infoBox') private _infoBoxRef: ElementRef;
```
Make you use what ever hash id you assign the ```<div #infoBox ...>``` (in this case infoBox) as the argument to the ViewChild directive.

**Comment by ghofrane111** [comment]
Hello,
Thank you for your solution, please can you give me the implementation of 
                            'bottom'
                            'top'
                            'right'
                            'left':
                            'topright':
                            'topleft':
                            'bottomright':
                            'bottomleft'

css classes ?? Thank you !
