### ISSUE TITLE
Infobox load error

### ISSUE THREAD

**Issue by drewteachout** [infusion-code/angular-maps#58]
I think this is a bug with x-info-box. I haven't found a way to consistently repeat it, but when I load my infoboxes occasionally they all end up like this.

![infobox_error](https://user-images.githubusercontent.com/20385315/33998074-7cdb4714-e0b4-11e7-9473-00b7ea6c604a.png)

It's like all the infoboxes were rendered all in one location. Also, if you mouse hover over them they slowly close out, but since there's about 50-100 of them it takes awhile for them to all close.

**Comment by thor-schueler** [comment]
Take a look at #38 and #57. If you have that many info boxes, it is better to consolidate into one infobox outside the markers. #57 has a basic approach sample (I will add a plunker sample too in the next few days). 

The behavior that you are seeing is more likely in the underlying Bing layer....

**Comment by drewteachout** [comment]
Do I just add this tag to the html?

`[IMarkerEvent]="click()"`

Or do I have to use angular's (click), and if so how do I know the lat and long of where I clicked?

**Comment by thor-schueler** [comment]
add

```
(MarkerClick)="ShowCard($event)"
```

to your x-map-marker. A click on the marker raises this event. It passes an ```IMarkerEvent``` to the handler... The ```IMarkerEvent``` contains, among other things, a handle to the Marker object, which has a copy of the Metadata you supplied on the marker, so you can pass arbitrary data through to the info box....

**Comment by drewteachout** [comment]
Is there a PolylineClick attribute? Or will the regular (click) work? I see there is a polyline event, but polyline has no metadata

**Comment by thor-schueler** [comment]
The Polyline has a click event. It actually is (Click) (capital C). Unfortunately, it currently emits only a MouseEvent. We have already refactored Polygon to emit an IPolygon Event and there is an IPolyline Event as well. We just have not had the chance yet to refactor Polyline to emit IPolyline yet as opposed to MouseEvent. The change is trivial and if you want to do it, please feel free to make the change and submit a PR. You can use the Polygon as a go by, the only change necessary is in AddEventListeners....

**Comment by thor-schueler** [comment]
@drewteachout - I have changed the polyline to emit IPolylineEvent instead of MouseEvent. That should solve your problem. The event has two properties: The original MouseEvent in the Click property and a reference to the emitting Polyline Component in the Polyline property. See PR #58. 

This is now part of version 0.8.0 (I reved the minor version since this is a potentially breaking change).
