### ISSUE TITLE
Marker layer Visible attribute doesn't work 

### ISSUE THREAD

**Issue by chuyelong** [infusion-code/angular-maps#60]
Just like code below, Change [Visible] attribute doesn't take effect.

`
//our root app component
import {Component, NgModule, VERSION} from '@angular/core'
import {BrowserModule} from '@angular/platform-browser'
import {MapModule, MapAPILoader, BingMapAPILoaderConfig, BingMapAPILoader, MarkerTypeId, IMapOptions, IBox, WindowRef, DocumentRef, MapServiceFactory, BingMapServiceFactory } from 'angular-maps';

@Component({
  selector: 'my-app',
  template: `
    <i class="fa"></i>
    <div style="height: 600px">
        <x-map #xmap [Options]="_options" [Box]="_box">
          <x-map-marker-layer [Visible]="_layerVisible">
            <x-map-marker *ngFor="let m of _markers; let i=index" [Latitude]="m.latitude" [Longitude]="m.longitude" [Title]="'My Marker ' + i.toString()" [IconInfo]="_iconInfo">
                <x-info-box [DisableAutoPan]="true" [Title]="'My InfoBox ' + i.toString()" [Description]="'Hi, this is the content of the <strong>info window</strong>. It is your responsibility to implement functionality such as close, etc...'">
                    <x-info-box-action [Label]="'Click Me'" (ActionClicked)="_click(i)"></x-info-box-action>
                </x-info-box>
            </x-map-marker>
          </x-map-marker-layer>
        </x-map>
    </div>
  `
})
export class App {
  _layerVisible: boolean = false;
  _markerTypeId = MarkerTypeId;
  _options: IMapOptions = {
    disableBirdseye: false,
    disableStreetside: false,
    navigationBarMode: 1, 
    zoom: 6
  };
  
  _box: IBox = {
    maxLatitude: 32,
    maxLongitude: -92,
    minLatitude: 29,
    minLongitude: -98
  };
  
  _iconInfo: IMarkerIconInfo = {
     markerType: MarkerTypeId.CanvasMarker,
     rotation: 45,
     drawingOffset: { x: 12, y: 0 },
     points: [
       { x: 5, y: 20 },
       { x: 12, y: 15 },
       { x: 19, y: 20 },
       { x: 12, y: 0 }
     ],
     color: '#f00',
     size: { width: 24, height: 24 }
};
  
  _markers: Array<ILatLong> = new Array<ILatLong>();
  
  constructor() {
    this._markers.push({ latitude: 29.714994, longitude: -95.46244})
    for(let i:number=0; i<20; i++){
      this._markers.push({ latitude: 29.714994 + Math.random() - Math.random(), longitude: -95.46244 + Math.random() - Math.random()});
    }      
  }
  
  _click(index: number){
     console.log(`Marker ${index} says: hello world...`);
  }
}

@NgModule({
  imports: [
    BrowserModule,
    MapModule.forRoot() 
  ],
  declarations: [ App ],
  providers: [
    { 
      provide: MapAPILoader, deps: [], useFactory: MapServiceProviderFactory
    }
  ],
  bootstrap: [ App ]
})
export class AppModule {}

export function MapServiceProviderFactory(){
    let bc: BingMapAPILoaderConfig = new BingMapAPILoaderConfig();
    bc.apiKey ="Ap0AObt84NcDaUThCeWOj52ZqUHv6k4TJhjLibR-DghC-semgoj-0uPbIi8r0E4j"; 
      // replace with your bing map key
      // the usage of this key outside this plunker is illegal. 
    bc.branch = ""; 
      // to use the experimental bing brach. There are some bug fixes for
      // clustering in that branch you will need if you want to use 
      // clustering.
    return new BingMapAPILoader(bc, new WindowRef(), new DocumentRef());
}
`

**Comment by thor-schueler** [comment]
@chuyelong  Please see http://plnkr.co/anhrCF for an example to toggle show/hide ```x-marker-layer``` on Bing. Can you be more specific on what does not work? Perhaps put together a plunker to illustrate and so that I can debug?

**Comment by thor-schueler** [comment]
I looked at this some more. It appears that there is a bug(?) in the Bing Maps ClusterLayer. Apparently, when the visibility of the layer is set to false, the adding markers to the layer will result in the markers 'getting lost'. 

This is probably what @chuyelong  is seeing. Starting out with ```_layerVisible = false``` will result in the markers added to the layer "getting lost". An immidiate workaround for this is to set ```_layerVisible = true``` and then set it to ```false``` during ```ngAfterContentInit``` with a delay of about 750ms (you might have to tweak that)...

I will look at a more robust solution...

**Comment by chuyelong** [comment]
Thanks @thor-schueler! :)

**Comment by thor-schueler** [comment]
@chuyelong : Just published 0.8.1. It contains fixes to the visibility issues in the ```x-marker-layer``` as well as some other clustering and layer related problems. It should remove the necessity for the workaround mentioned above. Please try and let me know...

**Comment by chuyelong** [comment]
Thanks @thor-schueler !
