### ISSUE TITLE
MapModule import error

### ISSUE THREAD

**Issue by hopkins700** [infusion-code/angular-maps#65]
Hi there!

I'm trying to import MapModule into my app module 

@NgModule({
    imports: [
        MapModule.forRoot()

but it causes the following error:

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the
function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol
 NgModule in /node_modules/angular-maps/node_modules/@angular/core/core.d.ts, resolving sym
bol MapModule in /node_modules/angular-maps/dist/index.d.ts, resolving symbol MapModule in
/node_modules/angular-maps/dist/index.d.ts

Any ideas how to make it work?

Thanks!

**Comment by thor-schueler** [comment]
@hopkins700 : This is interesting. We have stopped using lamdas in the factory functions a few releases back with the introduction of ng4. There are now static methods exported from the concrete factory implementations at https://github.com/infusion-code/angular-maps/blob/master/src/services/google/google-map.service.factory.ts and https://github.com/infusion-code/angular-maps/blob/master/src/services/bing/bing-map.service.factory.ts respectively. 

Take a look at any of the samples (https://github.com/infusion-code/angular-maps/wiki/Samples) or https://plnkr.co/1LdCQx to see how to wire it up. 

If you could post the version of angular maps you are using (you can find that in node_modules/angular-maps/package.json) as well as the entire code of your app module, that would be helpful to troubleshoot.

**Comment by tkostynyuk** [comment]
@hopkins700 :  This is the module:

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';
import { JsonpModule } from '@angular/http';
import { MapModule, MapAPILoader, BingMapAPILoaderConfig, BingMapAPILoader, WindowRef, DocumentRef, MapServiceFactory, BingMapServiceFactory } from "angular-maps";
import { PropMapComponent } from "./common/prop-map.component";


@NgModule({
    imports: [
        MapModule.forRoot(),
        CommonModule,
        FormsModule,
        ReactiveFormsModule,
        BrowserModule,
        RouterModule,
        JsonpModule
    ],
   declarations: [
       PropMapComponent
    ],
    entryComponents: [PropMapComponent],
    providers: [
        {
            provide: MapAPILoader, deps: [], useFactory: MapServiceProviderFactory
        }],
})
export class DealsModule { }

export function MapServiceProviderFactory(): BingMapAPILoader {
    let bc: BingMapAPILoaderConfig = new BingMapAPILoaderConfig();
    bc.apiKey = "Apd0GPr4DsBTSUYhYa7JFMZJNomTBiGGtwE85oK8J__Isoo3hWpLzQYT_R-jOEEJ"; 
    bc.branch = "experimental";
    return new BingMapAPILoader(bc, new WindowRef(), new DocumentRef());
}
 
Version of angular-maps is 0.8.2
![image](https://user-images.githubusercontent.com/18560382/35395256-e163fb44-01b7-11e8-95fd-04aca7383079.png)

Thanks!

**Comment by thor-schueler** [comment]
Ahh. Starting with 0.8.2 we are requiring at least ng@4.4.6. Could you please do the following:

1. uninstall angular-maps 0.8.2
2. upgrade ng to @4.4.6 or higher.
3. install angular-maps 0.8.2 

This should solve your problem. 

If you are not able to upgrade to ng@4.4.6, you can downgrade angular maps to @0.7.3, but you will loose out one some recent additions and fixes.

Also of note: bingmaps@2.0.2 seems to break the build, so make sure you only use bingmaps@2.0.0. I need to take a look at what MSFT changed there...

**Comment by tkostynyuk** [comment]
downgraded maps to maps to @0.7.3, and it worked. Thanks. Hopefully, we'll  upgrade to the latest version soon.

**Comment by thor-schueler** [comment]
let me know if it becomes and issue. I can lower the required ng version to 4.3.6... But it would be better for you to upgrade if possible...

**Comment by tkostynyuk** [comment]
the map works and displays a pin, but the initial focus is not on the pin. For example, the pin is in Asia but the map shows Africa, and you need to move it to see the pin. Are any samples available that use old @0.7.3 version?

Thanks for your help

**Comment by thor-schueler** [comment]
yes, all samples should work with 0.7.3. The get the focus where you want it, you need to set a bounding box. The sample at https://plnkr.co/T76hHj illustrates that. In the example, it set the bounding box on constructing, but it is a bound variable, so as new data comes in, you can easily calculate the bounding box as new data comes in. 

Alternatively to the bounding box, you can use the Latitude, Longitude and Zoom properties to focus the map. 

Either way will work, but I generally find bounding box a bit easier.
