### ISSUE TITLE
Cannot find namespace Microsoft

### ISSUE THREAD

**Issue by poojaguptez** [infusion-code/angular-maps#67]
error TS6053: File '/node_modules/bingmaps/types/MicrosoftMaps/Microsoft.Maps.All.d.ts' not found.`

Please update your installation instructions to also include a manual effort of executing 'npm install bingmaps' because angular-maps doesn't come with it out of the box.

**Comment by thor-schueler** [comment]
@poojaguptez: It is strange though since the package.json lists it as a dependency. So npm install after cloning the repo should install bingmaps without manual intervention. I take it that is not the behavior you are seeing?

Also got to update the dependency to version 2.x. Not terribly important, but should be done...

**Comment by thor-schueler** [comment]
This has been resolved by moving bing-maps from the peer dependencies to the dependencies.

**Comment by alikahwaji** [comment]
Hi @thor-schueler,

I'm getting thsame error above, TS2503: Cannot find namespace 'Microsoft'.  

ERROR in node_modules/angular-maps/src/models/bing/bing-canvas-overlay.d.ts(28,32): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-canvas-overlay.d.ts(35,15): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-canvas-overlay.d.ts(60,17): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-cluster-layer.d.ts(44,25): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-cluster-layer.d.ts(95,34): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-cluster-layer.d.ts(119,40): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-info-window.d.ts(26,30): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-info-window.d.ts(32,27): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-layer.d.ts(33,25): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-marker.d.ts(12,21): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-marker.d.ts(13,23): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-marker.d.ts(58,27): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-marker.d.ts(58,57): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-marker.d.ts(58,85): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-polygon.d.ts(13,23): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-polygon.d.ts(58,30): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-polygon.d.ts(90,27): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-polygon.d.ts(90,88): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-polyline.d.ts(11,21): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-polyline.d.ts(12,23): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-polyline.d.ts(36,30): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-polyline.d.ts(60,28): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-polyline.d.ts(60,59): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-polyline.d.ts(60,87): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/models/bing/bing-spider-cluster-marker.d.ts(7,12): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/services/bing/bing-map.service.d.ts(48,27): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/services/bing/bing-map.service.d.ts(55,34): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/services/bing/bing-map.service.d.ts(186,59): error TS2503: Cannot find namespace 'Microsoft'.
node_modules/angular-maps/src/services/bing/bing-polyline.service.d.ts(67,32): error TS2503: Cannot find namespace 'Microsoft'.

Here's my angular project version 

Angular CLI: 7.1.0
Node: 10.13.0
OS: linux x64
Angular: 7.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.1.0
@angular/cli                      7.1.0
@ngtools/webpack                  7.0.7
@schematics/angular               7.1.0
@schematics/update                0.11.0
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

I'm just trying to display a basic bing maps component on the localhost and I followed installation instructions on your npm page.
