### ISSUE TITLE
Incompatible with NG5 Angular App??

### ISSUE THREAD

**Issue by poojaguptez** [infusion-code/angular-maps#68]
Is angular-maps compatible with Ng5?
I have followed the exact instructions mentioned in your documentation, but my App throws this error:  compiler.js:486 Uncaught Error: Unexpected value 'MapModule' imported by the module 'AppModule'. Please add a @NgModule annotation. 

In my Angular App's package.json:  "angular/core": "^5.2.9"
In package.json of angular-maps module: "angular/core": "^4.4.6"

Is there a good resource online that I can follow for creating a angular-maps component in Ng5? I am interested in getting bingmaps basic implementation working.
thanks.

**Comment by METACEO** [comment]
I'm wanting to try building, packaging and publishing with [ng-packagr](https://www.npmjs.com/package/ng-packagr) - I think this would also help solve the Microsoft namespace issue, such as #67 (ng-packagr is used all throughout my client's codebase when it comes to sharing ng5 modules and components.)

**Comment by METACEO** [comment]
An update in regards to ng-packagr -  the annotations we have are resulting in warnings that break the ng-packagr build script (I omitted a lot of the entries out.)

Related issue that I'm involving myself in:
https://github.com/dherges/ng-packagr/issues/413

```
[root@base angular-maps]$ npm run package

> angular-maps@0.8.3 package /home/jamesallen/WebstormProjects/angular-maps
> ng-packagr -p package.json

Building Angular Package
Building entry point 'angular-maps'
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc

BUILD ERROR
src/interfaces/imarker-icon-info.ts(7,5): warning TS0: @type annotations are redundant with TypeScript equivalents
src/models/marker.ts(8,1): warning TS0: @interface annotations are redundant with TypeScript equivalents
src/models/marker.ts(14,5): warning TS0: @type annotations are redundant with TypeScript equivalents
src/models/marker.ts(22,5): warning TS0: @type annotations are redundant with TypeScript equivalents
src/models/marker.ts(31,1): warning TS0: @class annotations are redundant with TypeScript equivalents
src/models/marker.ts(44,5): warning TS0: @private annotations are redundant with TypeScript equivalents
@static annotations are redundant with TypeScript equivalents
@type annotations are redundant with TypeScript equivalents
src/models/marker.ts(55,5): warning TS0: @private annotations are redundant with TypeScript equivalents
@static annotations are redundant with TypeScript equivalents
@type annotations are redundant with TypeScript equivalents
src/models/marker.ts(65,5): warning TS0: @static annotations are redundant with TypeScript equivalents
the type annotation on @param is redundant with its TypeScript type, remove the {...} part

... many other entries ...

the type annotation on @param is redundant with its TypeScript type, remove the {...} part
the type annotation on @param is redundant with its TypeScript type, remove the {...} part
the type annotation on @return is redundant with its TypeScript type, remove the {...} part
src/services/google/google-map.service.factory.ts(117,5): warning TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part
the type annotation on @param is redundant with its TypeScript type, remove the {...} part
the type annotation on @return is redundant with its TypeScript type, remove the {...} part
src/services/google/google-map.service.factory.ts(130,5): warning TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part
the type annotation on @param is redundant with its TypeScript type, remove the {...} part
the type annotation on @return is redundant with its TypeScript type, remove the {...} part
src/services/google/google-map.service.factory.ts(145,1): warning TS0: the type annotation on @return is redundant with its TypeScript type, remove the {...} part
src/services/google/google-map.service.factory.ts(157,1): warning TS0: the type annotation on @return is redundant with its TypeScript type, remove the {...} part
```

**Comment by METACEO** [comment]
@thor-schueler - an update, FYI. I'm working on a branch for ng-packagr with an update here: https://github.com/infusion-code/angular-maps/commit/adc68fd2051f7e2662b917687cceea54bc779d74

With that branch you can run `npm run package` and see the output in the `dist` folder. Still working and testing to get everything ready to publish.

**Comment by tonysamperi** [comment]
This was my life-vest to include an Angular 5 app into an Ionic 3.9 app.
Now I'm screwed.

**Comment by METACEO** [comment]
Sorry to hear @tonysamperi - I'm having problems consuming the artifacts of the ng-packagr branch, while I'm having to work with what I can, I'm totally open to contributions or further direction: https://github.com/infusion-code/angular-maps/tree/using-ng-packagr

**Comment by thor-schueler** [comment]
@METACEO: for some reason I have not been getting the notifications, so I just caught up on this. If it helps, we can remove the annotations if the packager does not like them... Kinda sucks, but hey... Let's talk tomorrow, I'll be in the office.

**Comment by tonysamperi** [comment]
@METACEO actually I just noticed this stuff has nothing to do with what I'm doing...
And BTW I was able to compile. 
The problem for me was a `@type {EventEmitter}` in a couple components..I wasn't able to find those line because the compiler reported that the error was some lines below...

So **pay attention and whatch upper lines in your code**!!

**Comment by METACEO** [comment]
@thor-schueler - just pushed some final changes to the `using-ng-packagr` branch. I was able to publish an example here: [angular-maps-testing-ng6-build](https://www.npmjs.com/package/angular-maps-testing-ng6-build)
I'll reach out to you early this week regarding some publishing-related changes.

**Comment by thor-schueler** [comment]
@METACEO awesome!

**Comment by METACEO** [comment]
So far we're looking good - got an [ng4 environment](https://stackblitz.com/edit/angular4-nha6fc) consuming the ng6 testing build.

**Comment by jmsunseri** [comment]
when trying to publish an application using angular-maps-testing-ng6-build I get a fail to compile because

[0m[1m[31mERROR in ./node_modules/angular-maps-testing-ng6-build/angular-maps.ngfactory.js[39m[22m[0m
[0m[1m[31mModule not found(0,0): Error : Can't resolve 'angular-maps' in 'C:\Work\Pipeline Services\Crestwood.ProducerPortal\Crestwood.ProducerPortal.Web\ClientApp\node_modules\angular-maps-testing-ng6-build'[39m[22m[0m

**Comment by METACEO** [comment]
@thor-schueler - [just opened.](https://github.com/infusion-code/angular-maps/pull/72)

**Comment by thor-schueler** [comment]
We have just published angular maps 6.0.0 which should work with ng6... Leaving this issue open for a couple more days...

**Comment by thor-schueler** [comment]
I have moved over all the samples on the samples page to stackblitz and ng6 without any issues. So closing this issue as resolved. The only issues I have at this time is that stackblitz does not support (it appears) writing to the console from within an angular component...

**Comment by matheusdavidson** [comment]
My solution, in angular 7, was change my ```tsconfig.lib.json``` config, 

from this:
```json
"angularCompilerOptions": {
    "annotateForClosureCompiler": true
    ...
    ...
}
```
to this:
```json
"angularCompilerOptions": {
    "annotateForClosureCompiler": false
    ...
    ...
}
```
