### ISSUE TITLE
Q: Zoom in on click  

### ISSUE THREAD

**Issue by alikahwaji** [infusion-code/angular-maps#83]
Hi,

How can I zoom in on the maps when I click/select button or an asset to poplute a single location, I'm using bing maps (fetching the lat and long from a backend)? Is there any example that can be provided? 

Cheers 

Ali

**Comment by METACEO** [comment]
Hey @alikahwaji, I've forked one of our samples to include a button that will randomize the lat/lng/zoom: https://stackblitz.com/edit/bing-basic-map-with-single-marker-rvtl4s
Let me know what you think!

**Comment by alikahwaji** [comment]
Hi @METACEO,

Thanks for the sample, really helpful. 

Where can I find the docs for available angular-maps directives ?

Cheers 

Ali

**Comment by ahmedsaidzahran** [comment]
Nice sample, but I want to get Lat and Long from user click on map.
How to make

**Comment by thor-schueler** [comment]
@ahmedsaidzahran : check out #111 ...
