### ISSUE TITLE
scale map on box bound change

### ISSUE THREAD

**Issue by AxxitJdn** [infusion-code/angular-maps#93]
I have set an initial box:

`options = { bounds: { max and min latitude and longitude }}`

I want to change the bounds dynamically. Is this possible? I tried setting the xmap options e.g. by: `xmap.options.bounds = {new values}`

**Comment by thor-schueler** [comment]
don't directly reset bounds. Instead, update options (it is the observable). e.g:

xmap.options = { bounds: { new max and new min latitude and longitude }}

Instead of options, you can also Box input on the map component. That is a better approach...
