### ISSUE TITLE
@k-spen: actually, there is no ```<x-infobox>``` in this example. It's place has been taken by ```<div #infoBox ...>```

### ISSUE THREAD

**Issue by Piyush25071990** [infusion-code/angular-maps#95]
if we have multiple marker on map then it is showing multiple infobox.
how can i stop?

@k-spen: actually, there is no ```<x-infobox>``` in this example. It's place has been taken by ```<div #infoBox ...>```

To get a reference, use a ViewChild directive, as in 

```
    @ViewChild('infoBox') private _infoBoxRef: ElementRef;
```
Make you use what ever hash id you assign the ```<div #infoBox ...>``` (in this case infoBox) as the argument to the ViewChild directive.

_Originally posted by @thor-schueler in https://github.com/infusion-code/angular-maps/issues/57#issuecomment-352890009_

**Comment by thor-schueler** [comment]
I am not sure i understand your question. The example in #57 shows how to use one infobox shared by all markers. you can simply remove the <x-infobox> elements as they are not used in this situation.
