### ISSUE TITLE
How to add WMS layer using angular-maps

### ISSUE THREAD

**Issue by mourya09** [infusion-code/angular-maps#96]
Hi 

I am new to angular-maps and exploring the options of how to add WMS layer using angular-maps with google maps as base maps. Please help me in this regard.

**Comment by thor-schueler** [comment]
Have you made progress on this effort?

**Comment by mourya09** [comment]
Yes, I have to write my personal callback with ImageWMSLayer from google API. There was initial hiccups where it was getting trigger multiple times. 
https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/examples/maptype-image-overlay
