### ISSUE TITLE
Set The marker and infowindow in the center of the map on click

### ISSUE THREAD

**Issue by nabaragpaul** [infusion-code/angular-maps#97]
How can I set the marker and infowindow position in the center of the map if any marker gets clicked in the bing map. I am using custom infowindow and multiple markers. Thanks

**Comment by AxxitJdn** [comment]
Hello,
I created a custom infobox with some styling to set the box in the middle of the page :) 
Basically when a mapclick happens: ` (MapClick)="_mapClicked($event)" ` the correct infobox is displayed in the middle of the page

`<div #infoBox class="infoBox"
  [ngStyle]="{
    'visibility': _showBox ? 'visible' : 'hidden',
    'top': '50%', 
    'left': '50%',
    'position': 'absolute',
    'margin': '0',
    '-ms-transform': 'translate(-50%, -50%)',
    'transform': 'translate(-50%, -50%)' }">`
